//
import "reflect-metadata";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>BeginnersAppDev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className="w-full flex flex-col items-center justify-center py-2">
          <h1 className="mt-10 mb-4 text-4xl font-bold text-white">
            Enter to BeginnersAppDev
          </h1>
        </div>

      
         <div className={styles.description}>
         <h2>
          <a
            href="http://localhost:3001/api/doc"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            ➡️➡️➡️ Swagger documentation ⬅️⬅️⬅️
          </a>
          </h2>
        </div>
      </main>
    </>
  );
}
